# Generated by Django 3.1.3 on 2020-11-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('identificador', models.BigIntegerField()),
                ('email', models.CharField(max_length=45)),
                ('telefone', models.BigIntegerField()),
            ],
        ),
    ]
