# Generated by Django 3.1.3 on 2020-11-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='codigo',
        ),
    ]
