# Generated by Django 3.1.3 on 2020-11-23 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeContrato', models.CharField(max_length=60)),
                ('bioContrato', models.TextField(blank=True, null=True)),
                ('codigo', models.IntegerField()),
                ('valorContrato', models.FloatField(blank=True, max_length=45, null=True)),
                ('valorGasto', models.FloatField(blank=True, max_length=45, null=True)),
                ('profit', models.FloatField(blank=True, max_length=45, null=True)),
                ('dataContrato', models.DateField(blank=True, null=True)),
                ('dataEntrega', models.DateField(blank=True, null=True)),
                ('dataIncusao', models.DateTimeField(editable=False)),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='arquivos_contratos')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
