# Generated by Django 3.1.3 on 2020-11-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_remove_contrato_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='profit',
        ),
    ]
